In [2]:
import numpy as np
import torch
from tg.potential_game import PotGame

from tg.merging_game import pot_otherv, pot_mergerv, decode_sols, plot_game, GamePredictor,SubspacePredictor
from tg.merging_game import encode_sols2 as encode_sols

import tg.merging_game

import numpy as np
# from data import hee_preprocess2

from torch.multiprocessing import Pool, Process


use_deltav = True  # this indicates wheter the tgl-d method is used
dataset_name = "highD"
spacing = 5



from data import highD_preprocessing2 as highD_preprocessing
tracks = np.array([x[::spacing,:] for idx,x in highD_preprocessing.get_all_merge_tracks(extremefilter=True,mindelta=0,startpos=True,min_length=8*25)])
tracks[1]

# tracks = np.array([x[:8*5+1,:] for x in tracks])

Try to find the saved pickle file for better performance.
Found pickle file /Users/zhuhe/Desktop/Game/trajectory_games_learning/data/BoschData/highD/data/58.pickle.
{'id': 58, 'frameRate': 25, 'locationId': 6, 'speedLimit': 33.33, 'month': '7.2018', 'weekDay': 'Wed', 'startTime': '09:15', 'duration': 389.16, 'totalDrivenDistance': 274606.3, 'totalDrivenTime': 9301.0, 'numVehicles': 714, 'numCars': 582, 'numTrucks': 132, 'upperLaneMarkings': array([ 5.16,  8.71, 12.59, 15.71, 19.16]), 'lowerLaneMarkings': array([23.92, 27.2 , 30.57, 34.55])}
laneIds [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7

/Users/zhuhe/Desktop/Game/trajectory_games_learning/data/highD_preprocessing2.py:235: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x.append(np.array(xs))
/Users/zhuhe/Desktop/Game/trajectory_games_learning/data/highD_preprocessing2.py:235: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x.append(np.array(xs))


Found pickle file /Users/zhuhe/Desktop/Game/trajectory_games_learning/data/BoschData/highD/data/60.pickle.
{'id': 60, 'frameRate': 25, 'locationId': 6, 'speedLimit': -1.0, 'month': '7.2018', 'weekDay': 'Wed', 'startTime': '09:37', 'duration': 960.88, 'totalDrivenDistance': 585856.99, 'totalDrivenTime': 19961.08, 'numVehicles': 1467, 'numCars': 1137, 'numTrucks': 330, 'upperLaneMarkings': array([ 5.25,  8.79, 12.68, 15.88, 19.25]), 'lowerLaneMarkings': array([24.  , 27.29, 30.57, 34.63])}
laneIds [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 

/Users/zhuhe/Desktop/Game/trajectory_games_learning/data/highD_preprocessing2.py:235: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x.append(np.array(xs))
/Users/zhuhe/Desktop/Game/trajectory_games_learning/data/highD_preprocessing2.py:256: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(x)
/var/folders/d2/f3vm2qjs02ldnf3s8_w_jjd00000gn/T/ipykernel_97281/1953357886.py:23: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) 

array([[-4.02650000e+02,  8.99484536e-01, -3.24540000e+02,
         1.44329897e-01],
       [-3.97440000e+02,  9.04639175e-01, -3.20570000e+02,
         1.49484536e-01],
       [-3.92230000e+02,  9.09793814e-01, -3.16570000e+02,
         1.54639175e-01],
       [-3.87100000e+02,  9.12371134e-01, -3.12650000e+02,
         1.62371134e-01],
       [-3.81960000e+02,  9.14948454e-01, -3.08590000e+02,
         1.72680412e-01],
       [-3.76820000e+02,  9.14948454e-01, -3.04460000e+02,
         1.85567010e-01],
       [-3.71710000e+02,  9.14948454e-01, -3.00370000e+02,
         2.01030928e-01],
       [-3.66650000e+02,  9.14948454e-01, -2.96260000e+02,
         2.19072165e-01],
       [-3.61600000e+02,  9.12371134e-01, -2.92110000e+02,
         2.37113402e-01],
       [-3.56510000e+02,  9.12371134e-01, -2.87930000e+02,
         2.60309278e-01],
       [-3.51420000e+02,  9.09793814e-01, -2.83720000e+02,
         2.83505155e-01],
       [-3.46330000e+02,  9.07216495e-01, -2.79420000e+02,
      

In [3]:
from data import highD_preprocessing2 as highD_preprocessing
tracks = np.array([x[::spacing,:] for idx,x in highD_preprocessing.get_all_merge_tracks(extremefilter=True,mindelta=0,startpos=True,min_length=8*25)])
tracks = np.array([x[:8*5+1,:] for x in tracks])
pred_length = 7*5+1
eval_points = (np.array([1,2,3,4,5,6,7])*25)//5
avgx = np.mean(np.array([np.mean(x[1:,0]-x[0:-1,0]) for x in tracks]))
scaling = (np.array([1/avgx*3, 1, 1/avgx*3, 1])[None,:])
tracks = np.array([x*scaling for x in tracks])
scaling = torch.tensor(1 / scaling)
nhidden = 16


from sklearn.model_selection import KFold
kf = KFold(n_splits=4, random_state=0, shuffle=True)
print("Total tracks", len(tracks))
#这个数据真的

Try to find the saved pickle file for better performance.
Found pickle file /Users/zhuhe/Desktop/Game/trajectory_games_learning/data/BoschData/highD/data/58.pickle.
{'id': 58, 'frameRate': 25, 'locationId': 6, 'speedLimit': 33.33, 'month': '7.2018', 'weekDay': 'Wed', 'startTime': '09:15', 'duration': 389.16, 'totalDrivenDistance': 274606.3, 'totalDrivenTime': 9301.0, 'numVehicles': 714, 'numCars': 582, 'numTrucks': 132, 'upperLaneMarkings': array([ 5.16,  8.71, 12.59, 15.71, 19.16]), 'lowerLaneMarkings': array([23.92, 27.2 , 30.57, 34.55])}
laneIds [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7

/Users/zhuhe/Desktop/Game/trajectory_games_learning/data/highD_preprocessing2.py:235: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x.append(np.array(xs))
/Users/zhuhe/Desktop/Game/trajectory_games_learning/data/highD_preprocessing2.py:235: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x.append(np.array(xs))


Found pickle file /Users/zhuhe/Desktop/Game/trajectory_games_learning/data/BoschData/highD/data/60.pickle.
{'id': 60, 'frameRate': 25, 'locationId': 6, 'speedLimit': -1.0, 'month': '7.2018', 'weekDay': 'Wed', 'startTime': '09:37', 'duration': 960.88, 'totalDrivenDistance': 585856.99, 'totalDrivenTime': 19961.08, 'numVehicles': 1467, 'numCars': 1137, 'numTrucks': 330, 'upperLaneMarkings': array([ 5.25,  8.79, 12.68, 15.88, 19.25]), 'lowerLaneMarkings': array([24.  , 27.29, 30.57, 34.63])}
laneIds [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 

/Users/zhuhe/Desktop/Game/trajectory_games_learning/data/highD_preprocessing2.py:235: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x.append(np.array(xs))
/Users/zhuhe/Desktop/Game/trajectory_games_learning/data/highD_preprocessing2.py:256: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(x)
/var/folders/d2/f3vm2qjs02ldnf3s8_w_jjd00000gn/T/ipykernel_97281/753513710.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is

Total tracks 25


In [16]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=4, random_state=0, shuffle=True)
print("Total tracks", len(tracks))
train_idx, test_idx = list(kf.split(tracks))[1]

Total tracks 25


In [20]:
val_idx = train_idx[int(train_idx.shape[0]*0.6):]  #8
train_idx = train_idx[:int(train_idx.shape[0]*0.6)]  #11

tracks_train = tracks[train_idx]
tracks_val = tracks[val_idx]
tracks_test = tracks[test_idx]

In [25]:
tracks_train.shape
#11 个轨迹操作;


#41个时间点操作；

(11, 41, 4)

In [26]:
t_hist = 5
train_conds = encode_sols(tracks_train,offset = t_hist)

#不太清楚提取出来的数据是什么

/Users/zhuhe/Desktop/Game/trajectory_games_learning/tg/merging_game.py:434: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  ../torch/csrc/utils/python_arg_parser.cpp:882.)
  first_ind = (x[offset:,3] >= 0.5).nonzero()


In [43]:
for traj in tracks_train:
    track = torch.tensor(traj)
    # print(track)
    x = traj
    offset = 3
    first_ind = (x[offset:,3] >= 0.5).nonzero()

    #搞成了某种特殊的边吗；

(array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37]),)
(array([34, 35, 36, 37]),)
(array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37]),)
(array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37]),)
(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]),)
(array([30, 31, 32, 33, 34, 35, 36, 37]),)
(array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37]),)
(array([27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]),)
(array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37]),)
(array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37]),)
(array([31, 32, 33, 34, 35, 36, 37]),)


[[[0, tensor(11)],
  [tensor([-205.9662,    1.0412]),
   tensor([2.8923, 0.0058]),
   tensor([-183.1646,    0.1959]),
   tensor([3.0501, 0.0238]),
   3.7]],
 [[1, tensor(32)],
  [tensor([-187.4940,    1.1546]),
   tensor([3.0622e+00, 6.4433e-04]),
   tensor([-1.8787e+02, -4.4409e-16]),
   tensor([1.8896, 0.0026]),
   3.7]],
 [[1, tensor(11)],
  [tensor([-145.6129,    0.7938]),
   tensor([ 3.5447, -0.0103]),
   tensor([-185.3172,    0.2139]),
   tensor([2.4443, 0.0064]),
   3.7]],
 [[1, tensor(15)],
  [tensor([-179.7251,    1.0258]),
   tensor([3.4635, 0.0071]),
   tensor([-1.8502e+02,  8.5052e-02]),
   tensor([2.4834, 0.0071]),
   3.7]],
 [[1, tensor(8)],
  [tensor([-179.2140,    1.2113]),
   tensor([3.2816, 0.0039]),
   tensor([-1.8535e+02,  1.6237e-01]),
   tensor([2.5044, 0.0148]),
   3.7]],
 [[1, tensor(28)],
  [tensor([-164.2715,    0.9871]),
   tensor([ 3.8394e+00, -3.2216e-03]),
   tensor([-1.8467e+02,  4.3814e-02]),
   tensor([2.6412, 0.0077]),
   3.7]],
 [[1, tensor(10)],
  [t

In [3]:
import importlib
import tg.merging_game
importlib.reload(tg.merging_game)
thetam = torch.tensor([0., 0, 0, 0, 0, 0,1,1,0]) # is not used -
test_games = [PotGame(
    convex_ndims=4*(tracks_test[i].shape[0]-t_hist),
    player_utilities=(pot_otherv,pot_mergerv)
) for i in range(len(tracks_test))]



i= 1

pred_test_ss = []
for i in range(len(tracks_test)):
    subspace = ssp(torch.tensor(tracks_test[i][:t_hist,:]).float())
    print(i, "before_after", test_conds[i][0], subspace[0],  subspace[1], test_conds[i][1])
    pred_test_ss.append((np.argmax(subspace[0].detach().cpu()),int(subspace[1].detach().cpu())))



model = GamePredictor(thetam,2, None, t_hist=t_hist, nhidden=nhidden, nlayers = 2, velocity = 0, use_deltav=use_deltav)
sols = model(None, test_games[i],torch.tensor(tracks_test[i][:t_hist,:]).float(),pred_test_ss[i],test_conds[i][1], validate = validate, verbose=game_verbose, history_size = pred_size)

gt = tracks_test[0][t_hist:]


tg.merging_game.plot_game(sols,test_conds[1][1],gt)

NameError: name 'torch' is not defined